kyverno:
  policyReportsCleanup:
    enabled: false
  cleanupJobs:
    admissionReports:
      enabled: false
    clusterAdmissionReports:
      enabled: false
    ephemeralReports:
      enabled: false
    clusterEphemeralReports:
      enabled: false
    updateRequests:
      enabled: false
