apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signatures
  annotations:
    policies.kyverno.io/title: Verify Cosign Image Signatures
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy enforces that all images deployed into the online-boutique namespace
      are signed using Cosign keyless signing by our GitHub Actions CI pipeline.
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-signature
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - online-boutique
      verifyImages:
      - imageReferences:
        - "asia-south1-docker.pkg.dev/gke-argocd-425211/gke-argocd-repo/*"
        verifyDigest: true
        required: true
        mutateDigest: true
        keyless:
          subject: "https://github.com/Aishwaryaa12/gke-argocd/.github/workflows/boutique-ci.yaml@refs/heads/main"
          issuer: "https://token.actions.githubusercontent.com"
          rekor:
            url: "https://rekor.sigstore.dev"
