apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      # Use the Terraform outputs (e.g., project_id) to fill in these values
      projectID: <YOUR_PROJECT_ID>
      auth:
        workloadIdentity:
          clusterLocation: asia-south1-a
          clusterName: gke-argocd-cluster
          clusterProjectID: <YOUR_PROJECT_ID>
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
