apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db-password
  namespace: immich
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: immich-db-password-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich-db-password
